### ISSUE TITLE
Change URL to allow only english quotes

### ISSUE THREAD

**Issue by yashshah1** [gargakshit/gargakshit#3]
https://github.com/gargakshit/gargakshit/blob/265f37766312e529b1a85409400df258a3184566/index.js#L15

Change the URL to: https://programming-quotes-api.herokuapp.com/quotes/random/lang/en
to allow only English quotes

**Comment by gargakshit** [comment]
Sorry for the late reply, but thanks for the suggestion! Doing the same 🍻

**Comment by gargakshit** [comment]
https://github.com/gargakshit/gargakshit/blob/e1e906b4e623143a667f28777960fea3b494f6a1/index.js#L15
